version: 0.2

env:
  variables:
    S3_BUCKET: "calc-win-ubu-mac"
    APP_NAME: "calculator"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install pyinstaller
      - echo Install complete.

  build:
    commands:
      - echo Starting Windows build...

      # Create output directory
      - mkdir dist

      # Run PyInstaller to generate Windows .exe
      - pyinstaller --onefile --noconsole calculator.py --distpath dist

      # Confirm the build output
      - dir dist

      # Upload to S3
      - echo Uploading to S3...
      - aws s3 cp dist\calculator.exe s3://%S3_BUCKET%/builds/windows/

artifacts:
  files:
    - dist\calculator.exe
  discard-paths: yes
